{
  "id": "m8e9fc0m-2xnd",
  "errorLog": "API呼び出し中にエラーが発生しました: 不明なエラーが発生しました。",
  "status": "archived",
  "createdAt": "2025-03-18T08:57:07.222Z",
  "errorType": "不明なエラー",
  "relatedFiles": [],
  "investigationStartTime": "2025-03-18T08:57:07.223Z"
}